### ISSUE TITLE
@selector convert wrong

### ISSUE THREAD

**Issue by woshiccm** [LuizZak/SwiftRewriter#52]
[btn addTarget:self action:@selector(fullBtnClick:forEvent:) forControlEvents:UIControlEventTouchUpInside];

the result of action expression convert should be  #selector(fullBtnClick(_:forEvent:)), but now it is Selector("fullBtnClick:forEvent:")

**Comment by LuizZak** [comment]
This shouldn't be too difficult, an expression pass should do the job. I'll mark this as an enhancement and draft a pull request later!

**Comment by LuizZak** [comment]
Ok this might be a bit trickier than I thought at first. Seems like `#selector` expressions have a few extra syntactic rules like `#selector(getter:)` and `#selector(setter:)`. I'm creating a new `SelectorExpression` to support all the possible cases.

**Comment by LuizZak** [comment]
Can you checkout #53 and see if it works in your use case?
