### ISSUE TITLE
root manifest not found

### ISSUE THREAD

**Issue by FaizUlHassan123** [LuizZak/SwiftRewriter#56]
swift run -c=release SwiftRewriter files --colorize --target stdout /Users/a321/Documents/Github/CurvaView/CoreTextArcView.h  /Users/a321/Documents/Github/CurvaView/CoreTextArcView.m

**Comment by LuizZak** [comment]
What Swift version do you have installed, and which branch do you have cloned?

**Comment by FaizUlHassan123** [comment]
Branch Swift 5.5 and xcode 13 with swift 5.5

**Comment by LuizZak** [comment]
Make sure you are invoking the command from the terminal on the same folder as the `Package.swift` file from the cloned SwiftRewriter repository.

**Comment by FaizUlHassan123** [comment]
Thanks, I'll check it out.

**Comment by FaizUlHassan123** [comment]
Yes. Sent from my Huawei phone-------- Original message --------From: Luiz Fernando ***@***.***>Date: Sun, Oct 10, 2021, 4:18 AMTo: LuizZak/SwiftRewriter ***@***.***>Cc: Faiz Ul Hassan ***@***.***>, Mention ***@***.***>Subject: Re: [LuizZak/SwiftRewriter] root manifest not found (#56)
@FaizUlHassan123 did you manage to fix the issue?
